# Introducing Pandas Objects

먼저 3가지 Pandas 기본 구조인 ``Series``, ``DataFrame``, ``Index``을 살펴보기 위해 다음 두 패키지들을 import하자.

In [ ]:
import numpy as np
import pandas as pd

## The Pandas Series Object

``Series``는 1차원 array이며 list나 array를 통해 생성할 수 있다.

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

아래 두 결과에서 보듯이 ``Series`` object는 ``values`` 와 ``index``라는 속성(attributes)이 있다.
이 때, ``values``는 앞서 배운 NumPy array이다.

In [3]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

NumPy array처럼 기본적으로 simple index와 slicing으로 데이터를 접근할 수 있다.

In [5]:
data[1]

0.5

In [6]:
data[1:3]

1    0.50
2    0.75
dtype: float64

### ``Series`` as generalized NumPy array

``Series`` object 는 기본적으로 one-dimensional NumPy array이다.

그러나, 차이점은 index의 유무이다.
- Numpy array : *implicitly defined* integer index 
- Pandas ``Series`` : *explicitly defined* index

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

따라서 정수(integer)가 아닌 문자를 통해 indexing이 가능하다.

In [8]:
data['b']

0.5

또한 정수인 경우도 연속값일 필요가 없다.

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [10]:
data[5]

0.5

### Series as specialized dictionary

분명 Pandas ``Series``는 Python dictionary와 유사해 보인다. 하지만
- dictionary는 ``arbitrary key``로부터 ``arbitrary value``로의 map
- ``Series``는 ``typed keys``로부터 ``typed value`` 로의 map

다시 말해 `Series`가 더 빠르게 실행될 수 있다.

In [11]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

default로 ``Series``는 sorted key 형태로 index를 생성한다.

In [12]:
population['California']

38332521

dictionary와 달리 ``Series``는 array-style indexing을 지원한다. (예: slicing)

In [13]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

### Constructing Series objects

Recap) Pandas ``Series`` 생성 문법

```python
>>> pd.Series(data, index=index)
```

이 때, ``data``는 여러 형태의 데이터이지만 주로 list나 NumPy array와 같은 종류이며,  ``index``는 optional argument로서 default는 integer sequence이다.

In [ ]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

``data`` 는 scalar 값으로서 반복 채움형태로 사용될 수 있다.

In [ ]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

``data`` dictionary일 수 있으며 그러면  ``index``는  sorted dictionary key로 정의된다.

In [ ]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

``index``가 명시적으로 한정될 수 있다.

In [ ]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

## The Pandas DataFrame Object

### DataFrame as a generalized NumPy array
``DataFrame``은 NumPy의 two-dimensional array에 비유될 수 있으며 보다 flexible row indices 와 flexible column names을 갖는다.

``DataFrame``은 index를 공유하는 ``Series`` object들의 모임이라 할 수 있다.

In [14]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

앞서 ``population`` Series 와 index를 공유하는 DataFrame을 만들 수 있다.

In [15]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

``Series``처럼 ``DataFrame``은 ``index`` attribute가 있다.

In [16]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [17]:
states.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]])

추가적으로 ``DataFrame``은 ``columns`` attribute가 존재한다.

In [18]:
states.columns

Index(['population', 'area'], dtype='object')

In [20]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

### Constructing DataFrame objects

``DataFrame``은 아래 예들처럼 다양한 방식으로 생성할 수 있다.

#### From a single Series object

In [22]:
pd.DataFrame(population, columns=['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

#### From a list of dicts

In [ ]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

   a  b
0  0  0
1  1  2
2  2  4

dictionary내 일부 key의 값이 없어도 Pandas는 그것을 ``NaN`` (i.e., "not a number") 으로 채운 후 DataFrame을 생성한다.

In [ ]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

#### From a dictionary of Series objects

In [ ]:
pd.DataFrame({'population': population,
              'area': area})

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

#### From a two-dimensional NumPy array

In [ ]:
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

        foo       bar
a  0.460745  0.188837
b  0.526463  0.949458
c  0.883836  0.755497

#### From a NumPy structured array

In [ ]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
# i8 = int, f8 = float
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [ ]:
pd.DataFrame(A)

   A    B
0  0  0.0
1  0  0.0
2  0  0.0

## The Pandas Index Object

``Index`` object에 관련된 기능들을 살펴보자.

In [ ]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

### Index as immutable array

In [ ]:
ind[1]

3

In [ ]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [ ]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64

``Index`` object는 수정될 수 없는 immutable array이다.

In [ ]:
ind[1] = 0

TypeError: ignored

### Index as ordered set

``Index`` object는 Python's built-in ``set`` data structure를 따르므로 unions, intersections, differences 등 집합 연산이 가능하다.

In [ ]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [ ]:
indA & indB  # intersection

Int64Index([3, 5, 7], dtype='int64')

In [ ]:
indA | indB  # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [ ]:
indA ^ indB  # symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

사실 이러한 집합 연산은 object method로도 가능하다.
예) ``indA.intersection(indB)``.